# Automatically re-deploys the Cloud Run service on code change

steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/datastore-cleaner', '.']
# push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/datastore-cleaner']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'datastore-cleaner', '--image', 'gcr.io/$PROJECT_ID/datastore-cleaner', '--region', 'us-central1', '--platform', 'managed', '--quiet']
images: ['gcr.io/$PROJECT_ID/datastore-cleaner']
